# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  kube-rs:
    build:
      context: .
      dockerfile: Dockerfile
